export const types = {
    NEW_EVENTER_ENTRY: 'NEW_EVENTER_ENTRY',
    EVENTER_LIST: 'EVENTER_LIST',
    UPDATE_EVENTER_ENTRY: 'UPDATE_EVENTER_ENTRY',
    DELETE_EVENTER_ENTRY: 'DELETE_EVENTER_ENTRY',
    EVENTER_LIST_BY_ID: 'EVENTER_LIST_BY_ID'
}